package text

import "fmt"
var (
	blanco string = "\033[37m"
	verde string = "\033[32m"
	amarillo string = "\033[33m"
	azul string = "\033[36m"
)
func Logo(){
	fmt.Printf("   %v    ___  ___  ___  ___ ___ ___\n",azul)
	fmt.Printf("      |   || __||   ||_  ||  V  |\n")
	fmt.Printf("      | --|| |  | - ||  _| -   -\n")
	fmt.Printf("      |___||_|  |_|_||___|  |_|\n")
	fmt.Printf("   %v            ____    ___   ____\n",verde)
	fmt.Printf("              |     - -   - |    -\n")
	fmt.Printf("              |   0 ||     ||   0 |\n")
	fmt.Printf("              |  _-  |  0  ||  _-\n")
	fmt.Printf("              |_|     -___- |_|%v\n",blanco)
}
func Nmap(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Nmap                            |\n")
	fmt.Printf("   |es un programa de codigo abierto|\n")
	fmt.Printf("   |para efectuar rastreos de puerto|\n")
	fmt.Printf("   |originalmente escrito en c por  |\n")
	fmt.Printf("   |Gordon Lyon.                    |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Yow(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Yow                             |\n")
	fmt.Printf("   |crado por Juan Antonio Velasco  |\n")
	fmt.Printf("   |Gomez yow crea diccionarios de  |\n")
	fmt.Printf("   |palabras personalizadas. escrito|\n")
	fmt.Printf("   |en python 2.7                   |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Youtubedl(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Youtube-DL                      |\n")
	fmt.Printf("   |Software de linea de comandos   |\n")
	fmt.Printf("   |para descargar o extraer video y|\n")
	fmt.Printf("   |audio principalmente de youtube |\n")
	fmt.Printf("   |o cualquier paguina con video.  |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Moonbuggy(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Moon-Buggy                      |\n")
	fmt.Printf("   |Juego no grafico. principalmente|\n")
	fmt.Printf("   |saltas crateres por la luna. el |\n")
	fmt.Printf("   |el ganador es el que llegue mas |\n")
	fmt.Printf("   |lejos.                          |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Clamav(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |ClamAV                          |\n")
	fmt.Printf("   |Herramienta publicada bajo      |\n")
	fmt.Printf("   |licencia GNU te permite escanear|\n")
	fmt.Printf("   |software malicioso en terminal  |\n")
	fmt.Printf("   |Antivirus.                      |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Hydra(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |THC Hydra                       |\n")
	fmt.Printf("   |Es un software que realiza brute|\n")
	fmt.Printf("   |force a sistemas login de       |\n")
	fmt.Printf("   |diferentes servicios como HTTP, |\n")
	fmt.Printf("   |HTTPS, FTP,TELNET,IMAP,SMB y mas|\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("Nota: Si tiene un error al instalar hydra\n")
	fmt.Printf("puede instalarlo manual desde el link\n")
	fmt.Printf("https://github.com/vanhauser-thc/thc-hydra\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Ubuntu(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Ubuntu                          |\n")
	fmt.Printf("   |lo podras ejecutar en termux y  |\n")
	fmt.Printf("   |instalar software funcional en  |\n")
	fmt.Printf("   |ubuntu, No necesariamente ser   |\n")
	fmt.Printf("   |root.                           |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Kali(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Kali                            |\n")
	fmt.Printf("   |Puedes ejecutarlo desde termux  |\n")
	fmt.Printf("   |No necesariamente debes ser root|\n")
	fmt.Printf("   |y todo software podras instalar |\n")
	fmt.Printf("   |con Kali en tu terminal         |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Pacman(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |PacMan                          |\n")
	fmt.Printf("   |es una version del clasico juego|\n")
	fmt.Printf("   |pacman. como el original tendras|\n")
	fmt.Printf("   |de pacman a traves del laberinto|\n")
	fmt.Printf("   |comiendo todos los puntos       |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Freezer(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Freeze                          |\n")
	fmt.Printf("   |         ADVERTENCIA !!!        |\n")
	fmt.Printf("   |Es un malware programado en Hash|\n")
	fmt.Printf("   |Manejar con cuidado todo        |\n")
	fmt.Printf("   |software que afecte tu sistema  |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Darksploit(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Darksploit                      |\n")
	fmt.Printf("   |es una herramienta que contiene |\n")
	fmt.Printf("   |exploits y un escanner web      |\n")
	fmt.Printf("   |perfecto para defensores        |\n")
	fmt.Printf("   |creado por LOolzec.             |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Tor(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Tor                             |\n")
	fmt.Printf("   |The Onion Router lo puedes      |\n")
	fmt.Printf("   |ejecutar en el sistema, no      |\n")
	fmt.Printf("   |es necesario ser root           |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Weeman(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Weeman                          |\n")
	fmt.Printf("   |Crea servidores HTTP Phishing   |\n")
	fmt.Printf("   |en LocalHost de la red y clonar |\n")
	fmt.Printf("   |paginas web de todo tipo.       |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Crunch(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Crunch                          |\n")
	fmt.Printf("   |Crea Diccionarios numericos y   |\n")
	fmt.Printf("   |alfabeticos de cualquier peso   |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Debian(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Debian                          |\n")
	fmt.Printf("   |Debian GNU en tu sistema linux, |\n")
	fmt.Printf("   |ejecuta Debian en tu termux     |\n")
	fmt.Printf("   |no necesariamente ser root      |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Exiftool(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Exiftool                        |\n")
	fmt.Printf("   |printa y extrae informacion de  |\n")
	fmt.Printf("   |los metadatos de los archivos   |\n")
	fmt.Printf("   |y imagenes, tambien edita       |\n")
	fmt.Printf("   |y limpia de los datos exift     |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Gnupg(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Gnupg                           |\n")
	fmt.Printf("   |encrypta todo tipo de archivos  |\n")
	fmt.Printf("   |encrypta textos                 |\n")
	fmt.Printf("   |encrypta unidades extraibles    |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Cupp(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Cupp                            |\n")
	fmt.Printf("   |Creador de diccionarios         |\n")
	fmt.Printf("   |personalizados.                 |\n")
	fmt.Printf("   |                                |\n")
	fmt.Printf("   |   Creado por Mebus             |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Infoga(){
	Logo()
	fmt.Printf("    ________________________________\n")
	fmt.Printf("   |_CrazyPop______________[_][-][X]|\n")
	fmt.Printf("   |Infoga                          |\n")
	fmt.Printf("   |rastrea correos electronicos    |\n")
	fmt.Printf("   |relevando informacion servidor, |\n")
	fmt.Printf("   |reguion,etc.                    |\n")
	fmt.Printf("   |    Creador por m4ll0k          |\n")
	fmt.Printf("   |________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Phoneinfoga(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |PhoneInfoga                       |\n")
	fmt.Printf("   |Obten informacion de los numeros  |\n")
	fmt.Printf("   |celulares.                        |\n")
	fmt.Printf("   |pip -m install -r requirements.txt|\n")
	fmt.Printf("   |    Creador por ExpertAnonymous   |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Tmux(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Tmux                              |\n")
	fmt.Printf("   |Es un multiplexor de terminales   |\n")
	fmt.Printf("   |se basa en sesiones y abre        |\n")
	fmt.Printf("   |multiples ventanas, escrito en c  |\n")
	fmt.Printf("   |    Creador por Nicholas Marriott |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Torshammer(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Torshammer                        |\n")
	fmt.Printf("   |Es un script que ayuda a hacer    |\n")
	fmt.Printf("   |ataques DDOS por TOR.             |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Slowloris(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Slowloris                         |\n")
	fmt.Printf("   |basicamente es un ataque de       |\n")
	fmt.Printf("   |denegacion de servisio HTTP       |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |  escrito en perl en sus inicios  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Spiderbot(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Spiderbot                         |\n")
	fmt.Printf("   |Sitio web de Curl usando proxy    |\n")
	fmt.Printf("   |aleatorio y agente de usuario     |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |   creado por Cvar1984            |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Sqlmap(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Sqlmap                            |\n")
	fmt.Printf("   |es una herrameinta de inyeccion   |\n")
	fmt.Printf("   |sql y ataca servidores vulnerables|\n")
	fmt.Printf("   |en su base de datos.              |\n")
	fmt.Printf("   |   creado por sqlmapproject       |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Cmatrix(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Cmatrix                           |\n")
	fmt.Printf("   |background de la famosa pelicula  |\n")
	fmt.Printf("   |matrix.                           |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func W3m(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |w3m                               |\n")
	fmt.Printf("   |Navegador web No Grafico basado en|\n")
	fmt.Printf("   |texto asi como un paginador de    |\n")
	fmt.Printf("   |codigo abierto y lanzado 1995.    |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Htop(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |htop                              |\n")
	fmt.Printf("   |Es un systema de administracion   |\n")
	fmt.Printf("   |y monitoralizacion desde 2004 fue |\n")
	fmt.Printf("   |creado por Hisham Muhammad        |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Hashcat(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |hashcat                           |\n")
	fmt.Printf("   |hashcat es la utilidad de         |\n")
	fmt.Printf("   |recuperacion de password mas      |\n")
	fmt.Printf("   |rapida y avanzada del mundo       |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("Nota: Si tiene un error al instalar hashcat\n")
	fmt.Printf("puede instalarlo manual desde el link\n")
	fmt.Printf("https://github.com/hashcat/hashcat\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Lazymux(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Lazymux                           |\n")
	fmt.Printf("   |instala herramientas necesarias   |\n")
	fmt.Printf("   |para termux                       |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Wpspin(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Wpspin                            |\n")
	fmt.Printf("   |genera pin con mac de la redes con|\n")
	fmt.Printf("   |wps.                              |\n")
	fmt.Printf("   | python setup.py install          |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Commix(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Commix                            |\n")
	fmt.Printf("   |Nospermite atacar paginas web y   |\n")
	fmt.Printf("   |servidores, netcat, sin netcat    |\n")
	fmt.Printf("   |permite explotar e auditar el     |\n")
	fmt.Printf("   |servidor.                         |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Sms(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Spazsms                           |\n")
	fmt.Printf("   |Registra numeros celulares para   |\n")
	fmt.Printf("   |que lo bombarden de spam          |\n")
	fmt.Printf("   |en todo momento   :)              |\n")
	fmt.Printf("   | creado por Gameye98              |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Neofetch(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Neofetch                          |\n")
	fmt.Printf("   |Es un programa escrito en bash,   |\n")
	fmt.Printf("   |que permite ver en el terminal la |\n")
	fmt.Printf("   |informacion basica del sistema.   |\n")
	fmt.Printf("   |            open source           |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Flappy(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Flappy Bird                       |\n")
	fmt.Printf("   |Es un juego no grafico escrito en |\n")
	fmt.Printf("   |pythin 2.7 y lo unico que tienes  |\n")
	fmt.Printf("   |que evitar es chocar con los tubos|\n")
	fmt.Printf("   |que encontraras en el camino.     |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Vbug(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Vbug                              |\n")
	fmt.Printf("   |Es un script que te permite       |\n")
	fmt.Printf("   |descargar malware para windows,   |\n")
	fmt.Printf("   |android y apple.                  |\n")
	fmt.Printf("   |     creado por Gameye98          |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Routersploit(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Routersploit                      |\n")
	fmt.Printf("   |Permite hackear nuestro router    |\n")
	fmt.Printf("   |para comprobar la vulnerabilidad  |\n")
	fmt.Printf("   |del router.                       |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Blackhydra(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Black-Hydra                       |\n")
	fmt.Printf("   |herramienta de ataque bruteforce  |\n")
	fmt.Printf("   |ya con los comandos preprogramados|\n")
	fmt.Printf("   |realiza ataques en segundos.      |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("Nota: Si tiene un error al instalar hydra\n")
	fmt.Printf("puede instalarlo manual desde el link\n")
	fmt.Printf("https://github.com/vanhauser-thc/thc-hydra\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Websploit(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |Websploit                         |\n")
	fmt.Printf("   |es un proyecto de codigo abierto. |\n")
	fmt.Printf("   |para: Obras de ingenieria social. |\n")
	fmt.Printf("   |Web de escaneo, rastreador y      |\n")
	fmt.Printf("   |analisis.  Explotador automatico  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Astranmap(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |AstraNmap                         |\n")
	fmt.Printf("   |AstraNmap es un escaner de        |\n")
	fmt.Printf("   |seguridad que se utiliza para     |\n")
	fmt.Printf("   |encontrar hosts y servicios en una|\n")
	fmt.Printf("   |red informatica.  Requiere nmap   |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}
func Arat(){
	Logo()
	fmt.Printf("    __________________________________\n")
	fmt.Printf("   |_CrazyPop________________[_][-][X]|\n")
	fmt.Printf("   |A-Rat                             |\n")
	fmt.Printf("   |Shell inverso basado en A-Rat     |\n")
	fmt.Printf("   |(herramientas de administracion   |\n")
	fmt.Printf("   |remota) codificado por Xi4u7      |\n")
	fmt.Printf("   |                                  |\n")
	fmt.Printf("   |__________________________________|\n\n")
	fmt.Printf("   [%v1%v] %vinstall%v  [%v2%v] %vsalir%v  [%v3%v] %vregresar%v\n",verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco,verde,blanco,amarillo,blanco)
}